train: C:\Users\risho\Documents\GitHub\RoadSense\config\rdd2022\train\images
val: C:\Users\risho\Documents\GitHub\RoadSense\config\rdd2022\val\images

# Class information (this part is correct)
nc: 4
names: ["D00", "D10", "D20", "D40"]